#!/usr/bin/env node

const fs = require('fs');
const chalk = require('chalk');

const consoleMessages = {
  errorMessage: 'Your commit message did not match the pattern, please check the coding standards and try again.',
  successMessage: 'Your commit message meets the requirements.',
  acceptedFormats: `Accepted formats:
    feat(optional-scope): commit description example for features
    fix(optional-scope): commit description example for fixes
    chore(optional-scope): commit description example for cleanups`
}

const pattern = /^(feat|fix|chore)([(].+[)])?: .+$/i;
const commitMessage = fs.readFileSync(process.argv[2], 'utf8').trim();
const messageRegex = new RegExp(pattern);

if (messageRegex.test(commitMessage)) {
  console.log(chalk.green(consoleMessages.successMessage));
  process.exit(0);
} else {
  console.log(chalk.red(consoleMessages.errorMessage));
  console.log(chalk.red(`Your commit message: "${commitMessage}"`));
  console.log(chalk.blue(consoleMessages.acceptedFormats));
  process.exit(1);
}
